class Prefecture < ActiveHash::Base
  self.data = [
    { id:1, name: '--' },
    { id: 2, name: '北海道', name_english: 'hokkaido' },
    { id: 3, name: '青森県', name_english: 'aomori' },
    { id: 4, name: '岩手県', name_english: 'iwate' },
    { id: 5, name: '宮城県', name_english: 'miyagi' },
    { id: 6, name: '秋田県', name_english: 'akita' },
    { id: 7, name: '山形県', name_english: 'yamagata' },
    { id: 8, name: '福島県', name_english: 'fukushima' },
    { id: 9, name: '茨城県', name_english: 'ibaraki' },
    { id: 10, name: '栃木県', name_english: 'tochigi' },
    { id: 11,  name: '群馬県', name_english: 'gunma' },
    { id: 12,  name: '埼玉県', name_english: 'saitama' },
    { id: 13,  name: '千葉県', name_english: 'chiba' },
    { id: 14,  name: '東京都', name_english: 'tokyo' },
    { id: 15,  name: '神奈川県', name_english: 'kanagawa' },
    { id: 16,  name: '新潟県', name_english: 'nigata' },
    { id: 17,  name: '富山県', name_english: 'toyama' },
    { id: 18,  name: '石川県', name_english: 'ishikawa' },
    { id: 19,  name: '福井県', name_english: 'fukui' },
    { id: 20,  name: '山梨県', name_english: 'yamanashi' },
    { id: 21,  name: '長野県', name_english: 'nagano' },
    { id: 22,  name: '岐阜県', name_english: 'gifu' },
    { id: 23,  name: '静岡県', name_english: 'shizuoka' },
    { id: 24,  name: '愛知県', name_english: 'aichi' },
    { id: 25,  name: '三重県', name_english: 'mie' },
    { id: 26,  name: '滋賀県', name_english: 'shiga' },
    { id: 27,  name: '京都府', name_english: 'kyoto' },
    { id: 28,  name: '大阪府', name_english: 'osaka' },
    { id: 29,  name: '兵庫県', name_english: 'hyogo' },
    { id: 30,  name: '奈良県', name_english: 'nara' },
    { id: 31,  name: '和歌山県', name_english: 'wakayama' },
    { id: 32,  name: '鳥取県', name_english: 'tottori' },
    { id: 33,  name: '島根県', name_english: 'shimane' },
    { id: 34,  name: '岡山県', name_english: 'okayama' },
    { id: 35,  name: '広島県', name_english: 'hiroshima' },
    { id: 36,  name: '山口県', name_english: 'yamaguchi' },
    { id: 37,  name: '徳島県', name_english: 'tokushima' },
    { id: 38,  name: '香川県', name_english: 'kagawa' },
    { id: 39,  name: '愛媛県', name_english: 'ehime' },
    { id: 40,  name: '高知県', name_english: 'kochi' },
    { id: 41,  name: '福岡県', name_english: 'fukuoka' },
    { id: 42,  name: '佐賀県', name_english: 'saga' },
    { id: 43,  name: '長崎県', name_english: 'nagasaki' },
    { id: 44,  name: '熊本県', name_english: 'kumamoto' },
    { id: 45,  name: '大分県', name_english: 'oita' },
    { id: 46,  name: '宮崎県', name_english: 'miyazaki' },
    { id: 47,  name: '鹿児島県', name_english: 'kagoshima' },
    { id: 48,  name: '沖縄県', name_english: 'okinawa' }
  ]
end